baseURL = "/"
languageCode = "en-us"
title = "Kostas Tsalikis"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-112509011-1"

[params]
  bio = "Trials and tribulations of Android development"

  enableSummary = true
  useDescriptionReplaceSummary = true

  enableDisqus = true
  disqusShortname = "droidship-com"

  enableGoogleAnalytics = true

  iconFont = "font-awesome"

  enableShare = true

[social]
	facebook-square = "https://www.facebook.com/kostas.tsalikis.54"
	twitter-square = "https://twitter.com/tsalikispk"
	github-square = "https://github.com/tsalik"
  linkedin-square = "https://www.linkedin.com/in/kostas-tsalikis-400002126/"

[taxonomies]
  tag = "tags"
