baseURL = "https://www.droidship.com/"
languageCode = "en-us"
title = "Kostas Tsalikis"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-112509011-1"
pygmentsUseClasses=true
pygmentsCodefences=true
enableEmoji = true
Paginate = 5

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.speakerDeck]
    disable = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
    disableInlineCSS = true
  [privacy.vimeo]
    disable = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[params]
  bio = "Trials and tribulations of Android development"

  enableSummary = true
  useDescriptionReplaceSummary = true

  enableGoogleAnalytics = true

  iconFont = "font-awesome"

  enableShare = true
  enableRSS = true

[social]
	twitter-square = "https://twitter.com/tsalikispk"
	github-square = "https://github.com/tsalik"
  linkedin-square = "https://www.linkedin.com/in/kostas-tsalikis-400002126/"

[taxonomies]
  tag = "tags"

[services]
  [services.twitter]
    disableInlineCSS = true
